# Hands-On Data Lab

A practical Data Science lab covering NumPy, Pandas, data cleaning, visualization, and basic data analysis.

## Objective

This lab demonstrates a practical Data Science workflow using Python, covering numerical computing, data manipulation, data cleaning, visualization, and basic statistical analysis.

## Dataset

The Titanic passenger dataset is used for hands-on analysis. It contains passenger information such as survival status, passenger class, age, gender, fare, and embarkation port.

## Libraries and Tools

- Python
- Jupyter Notebook
- NumPy
- Pandas
- Matplotlib
- Seaborn

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## NumPy

NumPy provides efficient array-based operations for numerical computing in Python.

In [15]:
# Create a 1D NumPy array
array = np.array([1, 2, 3, 4, 5, 6])

array.ndim

1

In [16]:
# Create a 1D NumPy array
array.shape

(6,)

In [17]:
# Get the data type of the array
array.dtype

dtype('int64')

In [18]:
array[0]  # Access the first element of the array

np.int64(1)

In [19]:
# Access the last element of the array
array[-1]

np.int64(6)

In [20]:
# Access elements from index 1 to 3
array[1:4]  

array([2, 3, 4])

In [21]:
# Reverse the array
array[::-1]  

array([6, 5, 4, 3, 2, 1])

In [22]:
# Create a 2D NumPy array
array2 = np.array([[1, 2, 3], [4, 5, 6]])

array2.shape

(2, 3)

In [ ]:
# Reshape the array to the specified number of rows and columns
reshaped_array = array.reshape(2, 3)

reshaped_array.shape

(2, 3)

In [32]:
print("Original array:",array)
print("\nReshaped array:\n",reshaped_array)
print("\nShape of the reshaped array:",reshaped_array.shape)

Original array: [1 2 3 4 5 6]

Reshaped array:
 [[1 2 3]
 [4 5 6]]

Shape of the reshaped array: (2, 3)


In [ ]:
np.sum(array)  # Calculate the sum of all elements in the array

np.int64(21)

In [36]:
# Calculate the mean of all elements in the array
np.mean(array)

np.float64(3.5)

In [37]:
# Calculate the standard deviation of all elements in the array
np.std(array)

np.float64(1.707825127659933)

In [38]:
#
np.min(array)

np.int64(1)